package TempApp;


/**
* TempApp/TempCheckerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TempApp.idl
* Friday, March 5, 2021 7:08:35 o'clock PM BRT
*/

abstract public class TempCheckerHelper
{
  private static String  _id = "IDL:TempApp/TempChecker:1.0";

  public static void insert (org.omg.CORBA.Any a, TempApp.TempChecker that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TempApp.TempChecker extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TempApp.TempCheckerHelper.id (), "TempChecker");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TempApp.TempChecker read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TempCheckerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TempApp.TempChecker value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TempApp.TempChecker narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TempApp.TempChecker)
      return (TempApp.TempChecker)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TempApp._TempCheckerStub stub = new TempApp._TempCheckerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TempApp.TempChecker unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TempApp.TempChecker)
      return (TempApp.TempChecker)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TempApp._TempCheckerStub stub = new TempApp._TempCheckerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
