package TempApp;


/**
* TempApp/TempChecker.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TempApp.idl
* Friday, March 5, 2021 7:08:35 o'clock PM BRT
*/

public interface TempChecker extends TempCheckerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TempChecker
