package TempApp;


/**
* TempApp/TempCheckerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TempApp.idl
* Friday, March 5, 2021 7:08:35 o'clock PM BRT
*/

public interface TempCheckerOperations 
{
  String getCountries ();
  String convertCelsiusToF (String symbol);
} // interface TempCheckerOperations
