package TempApp;


/**
* TempApp/TempCheckerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TempApp.idl
* Friday, March 5, 2021 7:08:35 o'clock PM BRT
*/

public abstract class TempCheckerPOA extends org.omg.PortableServer.Servant
 implements TempCheckerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCountries", new Integer (0));
    _methods.put ("convertCelsiusToF", new Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TempApp/TempChecker/getCountries
       {
         String $result = null;
         $result = this.getCountries ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // TempApp/TempChecker/convertCelsiusToF
       {
         String symbol = in.read_string ();
         String $result = null;
         $result = this.convertCelsiusToF (symbol);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TempApp/TempChecker:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TempChecker _this() 
  {
    return TempCheckerHelper.narrow(
    super._this_object());
  }

  public TempChecker _this(org.omg.CORBA.ORB orb) 
  {
    return TempCheckerHelper.narrow(
    super._this_object(orb));
  }


} // class TempCheckerPOA
